// <auto-generated />
using System;
using Bank.Loan.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Loan.Api.Migrations;

[DbContext(typeof(LoanDbContext))]
[Migration("20241120040320_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Bank.Loan.Api.Entities.Events.LoanEvent", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnType("nvarchar(21)");

                b.Property<string>("LoanId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Metadata")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("datetime2");

                b.Property<int>("Version")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("LoanEvents", (string)null);

                b.HasDiscriminator<string>("EventType").HasValue("LoanEvent");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("Bank.Loan.Api.Entities.LoanEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("InterestRate")
                    .HasPrecision(5, 2)
                    .HasColumnType("decimal(5,2)");

                b.Property<decimal>("MonthlyPayment")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Loans", (string)null);
            });

        modelBuilder.Entity("Bank.Loan.Api.Entities.Events.LoanStatusChangedEvent", b =>
            {
                b.HasBaseType("Bank.Loan.Api.Entities.Events.LoanEvent");

                b.Property<int>("NewStatus")
                    .HasColumnType("int");

                b.Property<string>("Reason")
                    .HasColumnType("nvarchar(max)");

                b.HasDiscriminator().HasValue("LoanStatusChanged");
            });

        modelBuilder.Entity("Bank.Loan.Api.Entities.Events.LoanSubmittedEvent", b =>
            {
                b.HasBaseType("Bank.Loan.Api.Entities.Events.LoanEvent");

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasDiscriminator().HasValue("LoanSubmitted");
            });
#pragma warning restore 612, 618
    }
}
